const downloadHashHelp = "<details><summary>如何对比 SHA256？（以 Windows 为例）</summary><p>SHA256 是文件的校验码，可以理解成文件的“指纹”，用来核对安装包是否与官方提供的一致。</p><p>1. 在同一个版本的下载列表中，找到与你安装包完整名称对应的 .sha256 文件，用记事本打开，复制里面的 64 位校验码。它不是安装包，不需要安装。</p><p>2. 打开 PowerShell，输入下面的命令，将引号内的路径替换为你下载的安装包完整路径：</p><pre><code>Get-FileHash -LiteralPath \"C:\\Users\\你的用户名\\Downloads\\安装包.exe\" -Algorithm SHA256</code></pre><p>3. 将输出中 Hash 一栏的完整校验码与官方校验码逐位对比，英文字母大小写不影响结果。注意核对的是安装包本身，不是 .sha256 文件。</p><p>全部一致，表示文件内容一致；不一致时，先确认版本、系统和架构是否选对，再重新下载。Windows 7 若提示找不到 Get-FileHash，先按 Windows 7 教程升级 PowerShell 至 5.1。</p></details>";
import {commentsSection,validateComments} from './comments.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import {articles as baseArticles,groups} from '../content/articles.mjs';
import {withReleaseUpdates} from './article-updates.mjs';
import {explainRelease} from './releases.mjs';
import {validateServices,homeServices,servicesIndex,serviceDetail} from './services-view.mjs';
const mirror=JSON.parse(await fs.readFile('content/download-mirror.json','utf8'));
if(mirror.baseUrl && !/^https:\/\/[a-zA-Z0-9.-]+$/.test(mirror.baseUrl)) throw Error('Invalid mirror origin');
const services=JSON.parse(await fs.readFile('content/services.json','utf8'));
validateServices(services);
const site=JSON.parse(await fs.readFile('content/site.json','utf8'));
validateComments(site.comments);
const releases=JSON.parse(await fs.readFile('content/releases.json','utf8'));
const articles=withReleaseUpdates(baseArticles,releases);
const guideRedirects=JSON.parse(await fs.readFile('content/guide-redirects.json','utf8'));
const latest=releases.find(r=>!r.prerelease&&r.assets.some(a=>!a.name.endsWith('.sha256')));
if(!latest) throw Error('No stable release');
const out=path.resolve('dist');
// Only generated output is removed, after verifying its exact workspace path.
if(out!==path.join(process.cwd(),'dist')) throw Error('Unsafe output path');
await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});await fs.cp('public',out,{recursive:true});
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=[['/guide/','小白入门'],['/download/','下载中心'],['/manual/','功能手册'],['/learn/','工作原理'],['/troubleshoot/','问题排查'],['/changelog/','版本更新'],['/services/','机场推荐']];
const date=d=>d.slice(0,10);
const btn=(href,label,secondary=false)=>`<a class="button ${secondary?'secondary':''}" href="${href}">${label}<span aria-hidden="true">↗</span></a>`;
const shot=(name,alt)=>`<a class="zoom-image" href="/assets/screenshots/${name}.png"><img src="/assets/screenshots/${name}.png" alt="${alt}" width="1012" height="760" loading="lazy"></a>`;
const cards=items=>`<div class="card-grid">${items.map((a,i)=>`<a class="content-card" href="${a.path}"><span class="card-number">${String(i+1).padStart(2,'0')}</span><h3>${a.title}</h3><p>${a.description}</p><span class="card-link">开始阅读 <b aria-hidden="true">↗</b></span></a>`).join('')}</div>`;
const allPages=[];
function shell(title,description,body,current='/',toc=[]){
 const home=current==='/';
 return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}${home?'':' · Clash Party 中文指南'}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${site.origin}${current}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${site.origin}${current}"><meta property="og:type" content="${toc.length?'article':'website'}"><meta name="theme-color" content="#175de5"><link rel="icon" href="/assets/screenshots/logo.png"><link rel="stylesheet" href="/assets/style.css"><link rel="stylesheet" href="/assets/services.css"><script src="/assets/app.js" defer></script></head><body><a class="skip" href="#content">跳到正文</a><header class="header"><a href="/" class="brand"><img src="/assets/screenshots/logo.png" alt="" width="32" height="32"><span>Clash Party<small>中文指南</small></span></a><nav class="desktop-nav" aria-label="主导航">${nav.map(([url,t])=>`<a href="${url}" ${current.startsWith(url)?'aria-current="page"':''}>${t}</a>`).join('')}</nav><button class="search-toggle" aria-label="搜索教程">⌕ <span>搜索教程</span><kbd>/</kbd></button><button class="menu-toggle" aria-label="展开导航" aria-expanded="false">☰</button></header><nav class="mobile-nav" aria-label="移动导航" hidden>${nav.map(([url,t])=>`<a href="${url}">${t}</a>`).join('')}</nav>${body}<footer><div><a class="footer-brand" href="/">Clash Party 中文指南</a><p>从第一次安装，到理解每个设置。</p></div><div class="footer-links"><a href="/services/">服务推荐</a><a href="/about/">关于与推广说明</a><a href="https://github.com/mihomo-party-org/clash-party" target="_blank" rel="noopener noreferrer">官方 GitHub ↗</a><span>© ${site.contentDate.slice(0,4)} clashparty.online</span></div><p class="footer-disclaimer">独立维护 · 非官方网站，与 Clash Party 开发团队无隶属关系。</p></footer><dialog id="search-dialog" aria-labelledby="search-title"><div class="dialog-top"><h2 id="search-title">搜索中文指南</h2><button data-close aria-label="关闭搜索">✕</button></div><label class="sr-only" for="search-input">搜索关键词</label><input id="search-input" type="search" placeholder="试试：导入失败、虚拟网卡、Mac…" autocomplete="off"><p id="search-status" aria-live="polite">输入功能名称，或你遇到的问题。</p><div id="search-results"></div></dialog><dialog id="image-dialog" aria-label="查看操作大图"><button data-close aria-label="关闭大图">✕</button><img alt=""></dialog></body></html>`;
}
async function save(url,title,description,body,toc=[]){const file=url==='/'?'index.html':url==='404'?'404.html':`${url.slice(1)}index.html`; await fs.mkdir(path.dirname(path.join(out,file)),{recursive:true});await fs.writeFile(path.join(out,file),shell(title,description,body,url==='404'?'/404.html':url,toc));if(url!=='404')allPages.push({path:url,title,description});}
const latestInsights=explainRelease(latest);
const releaseSummary=latestInsights.slice(0,3).map(x=>x.title).join('、')||'查看官方发布变化';
await save('/','Clash Party 中文指南 · 下载、入门教程与版本解读','Clash Party 中文使用指南，提供 Windows、macOS、Linux 下载与入门教程、完整功能说明、工作原理、问题排查和版本更新解读。',`
<main id="content"><section class="hero"><div class="hero-copy"><div class="eyebrow"><span></span>CLASH PARTY · 中文使用指南</div><h1>从第一次连接，<br>到<span>用得明白。</span></h1><p class="hero-description">下载、导入、连接，一步一步来。<br>把复杂设置讲清楚，让每个问题有处可查。</p><div class="hero-actions">${btn('/guide/','开始使用')}${btn('/download/','下载 Clash Party',true)}</div><p class="hero-note">支持 Windows · macOS · Linux</p></div><div class="hero-visual"><div class="window-label"><span><i></i><i></i><i></i></span><b>先选节点，再开始连接</b><small>WINDOWS</small></div>${shot('system-proxy','Clash Party Windows 界面：规则模式与系统代理')}<div class="image-caption"><span>跟着步骤，轻松上手</span><a href="/guide/windows/">查看 Windows 图文教程 →</a></div></div></section>
<a class="release-ribbon" href="/changelog/${latest.version}/"><span class="pill">最新稳定版</span><strong>v${latest.version}</strong><span>${releaseSummary}</span><time>${date(latest.date)}</time><b>读懂本次更新 →</b></a>
<section class="section"><div class="section-heading"><div><div class="eyebrow">START HERE</div><h2>你的设备，从这里开始</h2></div><p>选择系统，跟着教程完成第一次连接。</p></div><div class="platform-grid">${[['⊞','Windows 11','兼顾 Windows 10 · x64 / ARM64','windows'],['⊞','Windows 7','兼顾 Windows 8 · 专用兼容包','windows-legacy'],['>_','Linux','DEB · RPM / CentOS · PACMAN','linux'],['⌘','Mac','Apple Silicon 与 Intel Mac','mac']].map(([icon,title,desc,slug])=>`<a class="platform-card" href="/guide/${slug}/"><span class="platform-icon">${icon}</span><div><h3>${title}</h3><p>${desc}</p></div><b>↗</b></a>`).join('')}</div><div class="under-links"><span>四篇平台教程，覆盖各自的芯片架构与安装方式。</span><a href="/guide/">查看全部入门教程 →</a></div></section>
<section class="start-strip"><div><span class="eyebrow">第一次使用？</span><h2>先跑通，再进阶。</h2></div><a href="/download/"><b>01</b><span>安装客户端<small>选对系统与架构</small></span></a><a href="/manual/subscription/"><b>02</b><span>导入订阅<small>准备自己的可用订阅</small></span></a><a href="/manual/system-proxy/"><b>03</b><span>选择节点并连接<small>从规则模式开始</small></span></a></section>

<section class="section split-section"><div><div class="section-heading"><div><div class="eyebrow">WHEN SOMETHING GOES WRONG</div><h2>卡在哪一步？</h2></div></div><p class="muted">从看到的现象出发，先检查，再调整。</p><div class="issue-list">${articles.filter(a=>['import','timeout','tun','offline-after-exit'].includes(a.slug)&&a.group==='troubleshoot').map(a=>`<a href="${a.path}">${a.title}<span>→</span></a>`).join('')}</div><a class="text-link" href="/troubleshoot/">查看全部问题排查 →</a></div><div class="learn-panel"><span class="eyebrow">UNDERSTAND THE WHY</span><h2>不只会点开关，<br>也知道为什么。</h2><p>系统代理和 TUN 有什么区别？<br>为什么节点延迟低，网站却很慢？</p><div class="mini-flow"><span>应用</span><b>→</b><span>内核与规则</span><b>→</b><span>目标网站</span></div><a href="/learn/" class="text-link">从工作原理开始了解 →</a></div></section>
<section class="section"><div class="section-heading"><div><div class="eyebrow">THE HANDBOOK</div><h2>需要时，随手可查</h2></div><a class="text-link" href="/manual/">全部功能手册 →</a></div><p class="muted"><a href="/manual/release-features/">查看 v${esc(latest.version)} 与历次功能变化 →</a></p>${cards(articles.filter(a=>a.group==='manual'&&['subscription','tun','dns','backup','smart','rules'].includes(a.slug)))}</section>
<section class="section updates-section"><div class="section-heading"><div><div class="eyebrow">WHAT’S NEW</div><h2>每次更新，了解变化</h2></div><a class="text-link" href="/changelog/">全部版本 →</a></div><div class="update-grid">${releases.filter(r=>!r.prerelease).slice(0,3).map(r=>`<a class="update-card" href="/changelog/${r.version}/"><time>${date(r.date)}</time><h3>Clash Party ${r.version}<span>↗</span></h3><p>${esc(explainRelease(r).slice(0,3).map(x=>x.title).join(' · ')||'官方版本变化与更新注意事项')}</p><small>查看变化与影响范围</small></a>`).join('')}</div></section>
</main>`);
for(const [group,title,desc] of groups){const items=articles.filter(a=>a.group===group);await save(`/${group}/`,title,desc,`<main id="content" class="container listing"><div class="breadcrumb"><a href="/">首页</a> / ${title}</div><div class="eyebrow">CLASH PARTY / ${group.toUpperCase()}</div><h1>${title}</h1><p class="lead">${desc}</p>${group==='guide'?'<aside class="callout">Clash Party 官方桌面版本覆盖 Windows、macOS 与 Linux。目前没有 iOS、iPadOS 或 Android 官方版本。按你的电脑系统选择教程，从安装开始逐步操作。</aside>':''}${group==='guide'?homeServices(services):''}${cards(items)}</main>`);}
for(const a of articles){const category=groups.find(g=>g[0]===a.group)[1];const peers=articles.filter(x=>x.group===a.group);const i=peers.indexOf(a);await save(a.path,a.title,a.description,`<main id="content" class="doc-layout"><aside class="sidebar"><a class="sidebar-heading" href="/${a.group}/">${category}</a>${peers.map(x=>`<a href="${x.path}" ${x===a?'aria-current="page"':''}>${x.title}</a>`).join('')}<div class="sidebar-bottom"><span>找不到答案？</span><a href="/troubleshoot/">从问题现象开始排查 →</a></div></aside><article class="article"><div class="breadcrumb"><a href="/">首页</a> / <a href="/${a.group}/">${category}</a></div><h1>${a.title}</h1><p class="lead">${a.description}</p><div class="article-meta"><span>操作示例 v${site.guideVersion}</span><span>更新于 ${a.releaseDate && a.releaseDate > site.contentDate ? a.releaseDate : site.contentDate}</span></div><div class="mobile-toc"><details><summary>本文目录</summary>${a.sections.map(s=>`<a href="#${s.id}">${s.title}</a>`).join('')}</details></div>${a.sections.map(s=>`<section id="${s.id}"><h2>${s.title}</h2>${s.html}</section>`).join('')}<aside class="source-note">参考来源：<a href="https://github.com/mihomo-party-org/clash-party/releases/tag/v${site.guideVersion}" target="_blank" rel="noopener noreferrer">v${site.guideVersion} 官方发布</a>。</aside><div class="feedback"><strong>这篇内容有帮助吗？</strong><div><button data-feedback="yes" data-page="${a.path}">解决了</button><button data-feedback="no" data-page="${a.path}">还没解决</button><button data-feedback="different" data-page="${a.path}">界面不一致</button></div><p class="feedback-message" aria-live="polite">${site.feedbackUrl?'反馈会引导至问题收集页。':'选择仅保存在本机，暂不发送给站点维护者。'}</p>${site.feedbackUrl?`<a href="${esc(site.feedbackUrl)}" target="_blank" rel="noopener noreferrer">提交详细反馈 ↗</a>`:''}</div>${a.group==='troubleshoot'?commentsSection(site.comments):''}<nav class="article-pagination" aria-label="相邻文章">${i>0?`<a href="${peers[i-1].path}"><small>上一篇</small>${peers[i-1].title}</a>`:'<span></span>'}${peers[i+1]?`<a href="${peers[i+1].path}"><small>下一篇</small>${peers[i+1].title} →</a>`:''}</nav></article><aside class="toc"><span>本页内容</span>${a.sections.map(s=>`<a href="#${s.id}">${s.title}</a>`).join('')}<a class="toc-back" href="#content">回到顶部 ↑</a></aside></main>`,a.sections);}

const platformGroups=[['windows','Windows 10 / 11','/guide/windows/',a=>a.name.includes('-windows-')],['win7','Windows 7 / 8','/guide/windows-legacy/',a=>a.name.includes('-win7-')],['macos','macOS 11+','/guide/mac/',a=>a.name.includes('-macos-')],['catalina','macOS Catalina 兼容包','/guide/mac/',a=>a.name.includes('-catalina-')],['linux','Linux','/guide/linux/',a=>a.name.includes('-linux-')]];
function assetLabel(a){let arch=/(?:arm64|aarch64)/.test(a.name)?'ARM64':/ia32/.test(a.name)?'32 位':'Intel / AMD 64 位';if(a.name.includes('-macos-')||a.name.includes('-catalina-'))arch=a.name.includes('arm64')?'Apple Silicon':'Intel';const kind=a.name.endsWith('.exe')?'安装版':a.name.endsWith('.7z')?'便携版':a.name.endsWith('.deb')?'DEB':a.name.endsWith('.rpm')?'RPM':a.name.endsWith('.zst')?'PACMAN':'PKG';return `${arch} · ${kind}`;}
await save('/download/','Clash Party 下载中心','选择 Windows、macOS 或 Linux 官方安装包，核对系统架构、版本与文件来源。',`<main id="content" class="container listing"><div class="breadcrumb"><a href="/">首页</a> / 下载中心</div><div class="eyebrow">OFFICIAL RELEASE FILES</div><h1>选对版本，再开始。</h1><p class="lead">稳定版 v${latest.version} · 发布于 ${date(latest.date)} · 安装包来自官方 GitHub。</p><div class="callout">不知道选哪个？Windows 在「系统信息」查看系统类型，Mac 在「关于本机」查看芯片，Linux 用 <code>uname -m</code> 查看架构。<strong>ARM64 是电脑架构，不是 iOS 版本。</strong></div><div data-mirror-base="${esc(mirror.baseUrl)}" data-version="${esc(latest.version)}"></div><script type="module" src="/assets/download-mirror.js"></script><nav class="filter-tabs" aria-label="筛选下载平台"><button data-platform="all" aria-pressed="true">全部平台</button>${platformGroups.map(([id,title])=>`<button data-platform="${id}" aria-pressed="false">${title}</button>`).join('')}</nav>${platformGroups.map(([id,title,guide,predicate])=>`<section class="download-platform" data-platform-section="${id}"><div class="section-heading"><h2>${title}</h2><a href="${guide}">查看安装教程 →</a></div>${id==='catalina'?'<p class="muted">Catalina 系统的 Intel Mac 选择 x64 包。官方还列出 arm64 兼容构建，但 Apple Silicon 不运行 Catalina 系统，请优先使用 macos-arm64 常规包。</p>':''}<div class="download-grid">${latest.assets.filter(a=>predicate(a)&&!a.name.endsWith('.sha256')).map(a=>{const hash=latest.assets.find(h=>h.name===a.name+'.sha256');return `<div class="download-card" data-mirror-name="${esc(a.name)}"><h3>${assetLabel(a)}</h3><p class="file-name">${esc(a.name)}</p><small>${(a.size/1024/1024).toFixed(1)} MiB · v${latest.version}</small><div class="download-actions"><a class="download-link" href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">官方下载 ↗</a>${hash?`<a class="download-checksum" href="${esc(hash.url)}" target="_blank" rel="noopener noreferrer">SHA256</a>`:''}</div></div>`;}).join('')}</div></section>`).join('')}<section class="article compact"><h2>下载前后的小提示</h2><ul><li><code>.sha256</code> 是校验文件，不是安装包；<code>latest.yml</code> 与源代码压缩包也不用于普通安装。</li><li>便携版完整解压后运行。PKG 用于 Mac，不能安装到 iPhone 或 iPad。</li><li>核对安装包的 SHA256，确认与官方提供的文件一致。${downloadHashHelp}</li><li>下载中心提供最新稳定版；阅读教程时，请留意文章注明的版本和系统差异。</li></ul><a href="${latest.url}" target="_blank" rel="noopener noreferrer">查看完整官方发布与历史版本 ↗</a></section></main>`);
await save('/changelog/','版本更新与中文解读','同步官方发布，了解每次更新影响谁、改了什么、更新后如何检查。',`<main id="content" class="container listing"><div class="breadcrumb"><a href="/">首页</a> / 版本更新</div><div class="eyebrow">RELEASE NOTES</div><h1>每次更新，了解变化。</h1><p class="lead">从官方记录出发，看看哪些变化与你有关。</p><div class="release-feature"><span class="pill">最新稳定版</span><h2>Clash Party ${latest.version}</h2><p>${releaseSummary}</p>${btn(`/changelog/${latest.version}/`,'阅读中文解读')}<small>发布于 ${date(latest.date)} · 已收录 ${releases.length} 个版本</small></div><aside class="callout">解读按官方说明中的主题自动归类，并提供对应检查建议；未识别的变化保留原文。不虚构实测结果，不把“修复与改进”扩写成未经确认的功能承诺。</aside><div class="timeline">${releases.map(r=>`<a href="/changelog/${r.version}/"><time>${date(r.date)}</time><div><h2>v${r.version} ${r.prerelease?'<span class="pill">预发布</span>':''}</h2><p>${esc(explainRelease(r).slice(0,4).map(x=>x.title).join(' · ')||'官方发布变化')}</p></div><b>→</b></a>`).join('')}</div></main>`);
for(const r of releases){const insights=explainRelease(r);await save(`/changelog/${r.version}/`,`Clash Party ${r.version} 更新与解读`,`${date(r.date)} 发布，查看官方变化、相关影响与升级检查。`,`<main id="content" class="container narrow article release-article"><div class="breadcrumb"><a href="/">首页</a> / <a href="/changelog/">版本更新</a> / ${r.version}</div><div class="eyebrow">${r.prerelease?'PRE-RELEASE':'RELEASE NOTES'}</div><h1>Clash Party ${r.version}<br>更新与中文解读</h1><div class="article-meta"><time>发布时间 ${date(r.date)}</time><span>${r.prerelease?'预发布版本':'正式发布'}</span><span>依据官方记录自动整理</span></div><aside class="callout">${r.prerelease?'这是预发布版本，新手优先使用下载中心的稳定版。':'以下影响说明是基于官方记录的分类解读，实际是否解决你的问题需要在对应系统验证。'}</aside><h2>这些变化与你有关吗？</h2>${insights.length?insights.map(x=>`<section class="insight"><h3>${esc(x.title)}</h3><p>${esc(x.explanation)}</p><details><summary>对应的官方变更（${x.evidence.length} 项）</summary><ul>${x.evidence.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></details><a href="${x.related}">查看相关教程 →</a></section>`).join(''):'<p>当前记录未匹配到可可靠解释的主题，请阅读下方官方说明。不会根据简短描述推测具体修复效果。</p>'}<h2>更新前后怎么检查</h2><ol><li>更新前保存配置备份，记录应用与内核版本。</li><li>从官方来源选择与你系统和架构匹配的安装包。</li><li>更新后检查订阅列表、代理组、系统代理和 TUN 状态。</li><li>重新访问常用网站。异常时记录错误并参考<a href="/troubleshoot/update/">升级排查</a>。</li></ol><h2>官方更新说明</h2><pre class="release-original">${esc(r.body||'本次发布未提供详细说明。')}</pre><p><a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">查看 GitHub 官方原始发布 ↗</a></p><div class="hero-actions">${btn('/download/','下载最新稳定版',true)}${btn('/changelog/','返回全部版本',true)}</div></main>`);}
await save('/services/','机场推荐：套餐与使用指南','了解99吧、FlyBit的套餐、流量与使用方式，了解如何导入Clash Party。',servicesIndex(services));
for(const s of services)await save(`/services/${s.slug}/`,`${s.name} 套餐与 Clash Party 使用教程`,s.description,serviceDetail(s));
await save('/about/','关于本站与推广说明','独立中文指南的维护范围、内容来源、推广说明与隐私信息。',`<main id="content" class="container narrow article listing"><h1>关于这份中文指南</h1><p class="lead">让第一次使用更容易，让每个设置更清楚。</p><h2>独立维护</h2><p>clashparty.online 是第三方中文指南，与 Clash Party 开发团队无隶属或授权关系。软件项目以官方 GitHub 为准。软件名称与标志属于相应权利人，本站使用其识别所讨论的项目。</p><h2>内容来源与维护</h2><p>版本事实来自官方 GitHub Releases。教程按安装、配置、连接和排错的操作顺序编写，并结合官方资料说明各项功能。不同系统与版本的界面可能略有不同，请按功能名称查找对应入口。</p><h2>个人信息与隐私</h2><p>教程中的订阅凭据与个人网络信息不予公开。本站搜索在浏览器中完成，文章帮助评价仅保存在当前设备，不会发送给维护者。本站不保存 GitHub 密码。问题排查页的评论通过 giscus 使用 GitHub 账号参与，留言与回复公开保存在 GitHub Discussions；加载评论时浏览器会连接 giscus 服务。本站没有广告追踪脚本、RSS 或邮件订阅。托管服务的访问日志由其平台管理。</p><h2>服务推荐</h2><p>推荐链接如产生佣金，会在对应位置说明；自营关系会独立披露。服务价格和限制以服务商当前信息为准。本站不承诺绝对稳定、特定速度或永久可用。</p><h2>软件问题反馈</h2><p>提交问题前，移除订阅令牌、账号、个人 IP 等敏感信息，并提供可复现步骤。<a href="https://github.com/mihomo-party-org/clash-party/issues" target="_blank" rel="noopener noreferrer">前往官方问题区 ↗</a></p></main>`);
await save('404','页面未找到','所查找的页面不存在。',`<main id="content" class="container narrow listing"><div class="eyebrow">404</div><h1>这条路还没找到。</h1><p class="lead">页面可能已移动。回到首页，或搜索你需要的功能。</p>${btn('/','返回首页')}<button class="button secondary search-toggle">搜索教程</button></main>`);
for(const [from,to] of Object.entries(guideRedirects)){
  if(!allPages.some(p=>p.path===to))throw Error(`Missing guide redirect target: ${to}`);
  const target=path.join(out,from.slice(1),'index.html');
  await fs.mkdir(path.dirname(target),{recursive:true});
  const html=shell('教程已合并','请前往合并后的平台教程。',`<main id="content" class="container narrow listing"><h1>教程已合并</h1><p><a href="${to}">继续阅读平台教程 →</a></p></main>`,to).replace('</head>',`<meta http-equiv="refresh" content="0;url=${to}"></head>`);
  await fs.writeFile(target,html);
}
await fs.writeFile(path.join(out,'_redirects'),Object.entries(guideRedirects).flatMap(([from,to])=>[`${from} ${to} 301`,`${from.slice(0,-1)} ${to} 301`]).join('\n')+'\n');
const index=allPages.map(p=>({...p,text:articles.find(a=>a.path===p.path)?.sections.map(s=>s.title+' '+s.html.replace(/<[^>]*>/g,' ')).join(' ')||p.description}));
await fs.writeFile(path.join(out,'search-index.json'),JSON.stringify(index));
await fs.writeFile(path.join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${allPages.map(p=>`<url><loc>${site.origin}${p.path}</loc></url>`).join('')}</urlset>`);
await fs.writeFile(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${site.origin}/sitemap.xml\n`);
await fs.writeFile(path.join(out,'_headers'),`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Content-Security-Policy: default-src 'self'; connect-src 'self' ${mirror.baseUrl}; img-src 'self'; script-src 'self' ${site.comments?.enabled?'https://giscus.app':''}; frame-src 'self' ${site.comments?.enabled?'https://giscus.app':''}; style-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'\n`);
console.log(`Built ${allPages.length} pages, ${articles.length} articles, ${releases.length} releases → dist/`);


