const serviceLogo=s=>s.logo?`<img class="service-mark service-logo" src="${e(s.logo)}" alt="${e(s.name)} Logo" width="55" height="55">`:`<span class="service-mark" aria-hidden="true">${e(s.name.slice(0,2))}</span>`;
const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const outbound=s=>`<a class="button" href="${e(s.url)}" target="_blank" rel="sponsored nofollow noopener noreferrer">访问 ${e(s.name)} ↗</a>`;
const disclosure='<p class="service-disclosure">部分链接含推广参数，本站可能获得佣金。套餐、试用与优惠以服务商结算页为准。</p>';
export function validateServices(services){
 const slugs=new Set();
 for(const s of services){if(!/^[a-z0-9-]+$/.test(s.slug)||slugs.has(s.slug))throw Error('Invalid or repeated service slug');slugs.add(s.slug);for(const key of ['url','source'])if(new URL(s[key]).protocol!=='https:')throw Error('Service links must use HTTPS');if(!s.name||!s.plans?.length)throw Error('Service data incomplete');}
}
export function serviceCards(services){return `<div class="recommendation-grid">${services.map(s=>`<section class="recommendation"><div class="service-heading">${serviceLogo(s)}<div><span class="eyebrow">${e(s.label)}</span><h3>${e(s.name)}</h3></div></div><p>${e(s.description)}</p><div class="service-price"><span>¥</span><strong>${e(s.price)}</strong><span>/ 月</span><small>${e(s.allowance)}</small></div><ul class="service-tags">${s.tags.map(t=>`<li>${e(t)}</li>`).join('')}</ul><p class="trial">试用：${e(s.trial)}</p><div class="hero-actions">${outbound(s)}<a class="button secondary" href="/services/${s.slug}/">套餐与使用说明 →</a></div></section>`).join('')}</div>`;}
export function homeServices(services){return `<section class="section home-services"><div class="section-heading"><div><div class="eyebrow">CHOOSE YOUR SUBSCRIPTION</div><h2>准备一份适合自己的订阅</h2></div><a class="text-link" href="/services/">查看机场推荐 →</a></div><p class="muted">已有可用订阅？可以直接<a href="/manual/subscription/">导入 Clash Party</a>。还没有订阅，可先了解下面的服务。</p>${serviceCards(services)}${disclosure}</section>`;}
export function servicesIndex(services){return `<main id="content" class="container listing"><div class="breadcrumb"><a href="/">首页</a> / 机场推荐</div><div class="eyebrow">SUBSCRIPTION GUIDE</div><h1>先选订阅，再开始连接。</h1><p class="lead">从预算、流量和设备需求出发，选择适合自己的套餐。</p>${serviceCards(services)}${disclosure}<section class="article compact"><h2>月付还是不限时？</h2><p>每月都有固定需求，可以先从月付开始；只是偶尔使用或备用，可以考虑不限时流量包。年付虽然可能更优惠，但需一次支付较多费用，建议先验证自己的网络再决定。</p><h2>选好以后，怎么用 Clash Party？</h2><ol><li>登录服务商用户中心，在「仪表盘」找到「一键订阅」，展开菜单后点击「复制订阅地址」。不同服务商的入口名称可能略有不同。<figure><a class="zoom-image" href="/assets/services/copy-subscription.jpg"><img src="/assets/services/copy-subscription.jpg" alt="在仪表盘的一键订阅菜单中点击复制订阅地址" width="1200" height="673" loading="lazy"></a><figcaption>展开「一键订阅」，点击「复制订阅地址」。</figcaption></figure></li><li>打开「订阅管理」，粘贴完整地址并导入。</li><li>选择可用节点，开启系统代理并访问目标网站验证。</li></ol><p><a href="/guide/">按系统查看入门教程 →</a> · <a href="/manual/subscription/">查看订阅导入步骤 →</a></p><h2>购买前确认</h2><p>两家服务均不支持退款。购买前先查看试用条件，核对套餐总价、流量周期、设备限制与售后规则。虽然本站已测试，但线路、速度以及流媒体与 AI 服务的可用性后续可能变动，建议先试用，再用自己的网络和设备验证常用服务是否可用。</p></section></main>`;}
export function serviceDetail(s){return `<main id="content" class="container narrow article listing"><div class="breadcrumb"><a href="/">首页</a> / <a href="/services/">机场推荐</a> / ${e(s.name)}</div>${serviceLogo(s)}<div class="eyebrow">${e(s.label)}</div><h1>${e(s.name)}：套餐与 Clash Party 使用说明</h1><p class="lead">${e(s.description)}</p><div class="hero-actions">${outbound(s)}<a class="button secondary" href="#plans">查看套餐</a></div>${disclosure}<h2>适合怎样的使用需求</h2><ul>${s.suitable.map(x=>`<li>${e(x)}</li>`).join('')}</ul><div class="service-facts">${[['试用',s.trial],['设备',s.devices],['协议',s.protocol],['线路',s.routes],['节点数量',s.nodes],['支付',s.payment]].map(([k,v])=>`<div><small>${k}</small><strong>${e(v)}</strong></div>`).join('')}</div><p class="service-disclosure">以上为公开服务资料，节点数量与线路情况可能变化，实际以服务商当前说明为准。</p><h2 id="plans">套餐与流量</h2><p>月付与年付是付款周期；“GB / 月”表示每月流量，“总流量”表示一次性流量额度。</p><div class="table-scroll" tabindex="0" role="region" aria-label="${e(s.name)}套餐价格"><table><thead><tr><th scope="col">套餐</th><th scope="col">价格</th><th scope="col">流量</th><th scope="col">说明</th></tr></thead><tbody>${s.plans.map(p=>`<tr><th scope="row">${e(p.name)}<small>${e(p.period)}</small></th><td>${e(p.price)}</td><td>${e(p.traffic)}</td><td>${e(p.note)}</td></tr>`).join('')}</tbody></table></div><p>${e(s.billing)}</p><aside class="callout">可在结算页尝试优惠码 <strong class="coupon">${e(s.coupon)}</strong>，确认实际抵扣金额后再支付。此处不保证所有套餐、账号或活动均可使用。</aside><h2>导入 Clash Party</h2><ol class="steps"><li>登录 ${e(s.name)} 的用户中心，找到订阅入口，复制适用于 Clash / Mihomo 的完整订阅链接。</li><li>打开 Clash Party「订阅管理」，粘贴地址并点击「导入」。不要复制登录页或带邀请码的注册链接。</li><li>出现订阅卡片后选中它，打开「代理组」，先测试机场名称对应的组并选一个可用节点。</li><li>日常先用规则模式和系统代理；若使用全局模式且 GLOBAL 测速异常，先测机场名称组，再回到 GLOBAL 测试并检查实际出口。</li><li>访问常用网站验证连接。不要公开自己的订阅地址。</li></ol><div class="platform-tutorial-links"><a href="/guide/windows/">Windows 11</a><a href="/guide/windows-legacy/">Windows 7</a><a href="/guide/mac/">Mac</a><a href="/guide/linux/">Linux</a></div><h2>购买与使用前注意</h2><ul><li>参考资料注明：${e(s.refund)}。</li>${s.notes.map(n=>`<li>${e(n)}</li>`).join('')}<li>流媒体和 AI 服务的可用性会随节点 IP 与平台策略变化，请先测试自己的常用服务。</li></ul><p>如果导入失败，先检查链接格式和套餐状态，再阅读<a href="/troubleshoot/import/">订阅导入排查</a>。已导入但无法连接，查看<a href="/troubleshoot/timeout/">节点超时排查</a>。</p><div class="hero-actions">${outbound(s)}<a class="button secondary" href="/services/">返回机场推荐</a></div><p class="source-note">套餐与服务资料参考：<a href="${e(s.source)}" target="_blank" rel="noopener noreferrer">${e(s.name)} 服务资料</a>（更新于 ${e(s.sourceDate)}）；本站查阅于 ${e(s.checkedAt)}。价格及优惠以结算页为准。</p></main>`;}
